/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.interfaces2.proveedores;

import com.proyecto.DAO.ProveedorDAO;
import com.proyecto.interfaces2.*;
import com.proyecto.modelo.Usuario;

/**
 *
 * @author alexa
 */
public class VerProveedores extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    Usuario usuario = new Usuario();
    ProveedorDAO proveedorDAO = new ProveedorDAO();

    public VerProveedores(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        jTableProveedores.setModel(proveedorDAO.tabla());
    }

    public VerProveedores() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENERAL = new javax.swing.JPanel();
        LEFT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedores = new javax.swing.JTable();
        RIGHT = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        idProveedor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSalirP = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnModificarP = new javax.swing.JButton();
        btnEliminarP = new javax.swing.JButton();
        btnAgregarPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GENERAL.setBackground(new java.awt.Color(0, 204, 204));
        GENERAL.setForeground(new java.awt.Color(0, 204, 204));
        GENERAL.setPreferredSize(new java.awt.Dimension(900, 600));
        GENERAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GENERALMouseClicked(evt);
            }
        });
        GENERAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LEFT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Moon-Korean");
        LEFT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        Name.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Proveedores");
        LEFT.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../img/headCliente.png"))); // NOI18N
        LEFT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 170));

        jTableProveedores
                .setModel(new javax.swing.table.DefaultTableModel(
                        new Object[][] { { null, null, null, null }, { null, null, null, null },
                                { null, null, null, null }, { null, null, null, null } },
                        new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
        jScrollPane1.setViewportView(jTableProveedores);

        LEFT.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 450));

        GENERAL.add(LEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        RIGHT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GENERAL.add(RIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Usuario:");
        GENERAL.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 244, -1, 10));
        GENERAL.add(idProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Contraseña:");
        GENERAL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 10));

        btnSalirP.setBackground(new java.awt.Color(255, 255, 255));
        btnSalirP.setText("SALIR");
        btnSalirP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirPMouseClicked(evt);
            }
        });
        btnSalirP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPActionPerformed(evt);
            }
        });
        GENERAL.add(btnSalirP, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../img/usuarios-table.png"))); // NOI18N
        jLabel12.setText("ID");
        GENERAL.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 200, 150));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID");
        GENERAL.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 40, -1));

        btnModificarP.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarP.setText("MODIFICAR");
        btnModificarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarPMouseClicked(evt);
            }
        });
        GENERAL.add(btnModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, -1, -1));

        btnEliminarP.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminarP.setText("ELIMINAR");
        btnEliminarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPMouseClicked(evt);
            }
        });
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });
        GENERAL.add(btnEliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 90, -1));

        btnAgregarPro.setText("AGREGAR");
        btnAgregarPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProMouseClicked(evt);
            }
        });
        GENERAL.add(btnAgregarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                GENERAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(GENERAL, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSalirPMouseClicked
        if(usuario.getAdmin()){
            Menu m = new Menu(usuario);
            m.setVisible(true);
            this.setVisible(false);
        }else{
            Menu2 m = new Menu2(usuario);
            m.setVisible(true);
            this.setVisible(false);
        }
    }// GEN-LAST:event_btnSalirPMouseClicked

    private void btnModificarPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnModificarPMouseClicked
        ModificarProveedor mod = new ModificarProveedor(usuario);
        mod.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_btnModificarPMouseClicked

    private void btnSalirPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirPActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnSalirPActionPerformed

    private void btnEliminarPMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnEliminarPMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEliminarPMouseClicked

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEliminarPActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnEliminarPActionPerformed

    private void btnAgregarProMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnAgregarProMouseClicked
        RegistrarProveedores rp = new RegistrarProveedores();
        rp.setVisible(true);
        this.setVisible(false);
    }// GEN-LAST:event_btnAgregarProMouseClicked

    private void GENERALMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_GENERALMouseClicked
        // TODO add your handling code here:
    }// GEN-LAST:event_GENERALMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GENERAL;
    private javax.swing.JPanel LEFT;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel RIGHT;
    private javax.swing.JButton btnAgregarPro;
    private javax.swing.JButton btnEliminarP;
    private javax.swing.JButton btnModificarP;
    private javax.swing.JButton btnSalirP;
    private javax.swing.JTextField idProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProveedores;
    // End of variables declaration//GEN-END:variables
}
