/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.interfaces2.users;

import com.proyecto.DAO.UsuarioDAO;
import com.proyecto.interfaces2.*;
import com.proyecto.modelo.Usuario;
import static javax.swing.JOptionPane.showMessageDialog;
/**
 *
 * @author alexa
 */
public class VerUsers extends javax.swing.JFrame {
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    /**
     * Creates new form interfaz
     */
    Usuario usuario = new Usuario();
    
    public VerUsers(Usuario u){
        this.usuario=u;
        initComponents();
        this.setLocationRelativeTo(null);
        jTableUsers.setModel(usuarioDAO.tabla());
    }
    public VerUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENERAL = new javax.swing.JPanel();
        LEFT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        RIGHT = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSalirU = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnModificarU = new javax.swing.JButton();
        btnEliminarU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GENERAL.setBackground(new java.awt.Color(0, 204, 204));
        GENERAL.setForeground(new java.awt.Color(0, 204, 204));
        GENERAL.setPreferredSize(new java.awt.Dimension(900, 600));
        GENERAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LEFT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Moon-Korean");
        LEFT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../img/headCliente.png"))); // NOI18N
        LEFT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 170));

        jTableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableUsers);

        LEFT.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 450));

        GENERAL.add(LEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        RIGHT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GENERAL.add(RIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Usuario:");
        GENERAL.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 244, -1, 10));
        GENERAL.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Contraseña:");
        GENERAL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 10));

        btnSalirU.setBackground(new java.awt.Color(0, 204, 204));
        btnSalirU.setText("SALIR");
        btnSalirU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirUMouseClicked(evt);
            }
        });
        btnSalirU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirUActionPerformed(evt);
            }
        });
        GENERAL.add(btnSalirU, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../img/usuarios-table.png"))); // NOI18N
        jLabel12.setText("ID");
        GENERAL.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 200, 150));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID");
        GENERAL.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 40, -1));

        btnModificarU.setBackground(new java.awt.Color(0, 204, 204));
        btnModificarU.setText("MODIFICAR");
        btnModificarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarUMouseClicked(evt);
            }
        });
        GENERAL.add(btnModificarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        btnEliminarU.setBackground(new java.awt.Color(0, 204, 204));
        btnEliminarU.setText("ELIMINAR");
        btnEliminarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarUMouseClicked(evt);
            }
        });
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });
        GENERAL.add(btnEliminarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GENERAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GENERAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirUMouseClicked
        if(usuario.getAdmin()){
            Menu m = new Menu(usuario);
            m.setVisible(true);
            this.setVisible(false);
        }else{
            Menu2 m = new Menu2(usuario);
            m.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnSalirUMouseClicked

    private void btnModificarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarUMouseClicked
        String id;
        id=jTextField1.getText();
        if(id.length()!=0){
            Usuario usuario1 = usuarioDAO.buscar(Integer.parseInt(id));
            if(usuario1!=null){
            Modificar mod = new Modificar(usuario, usuario1);
            mod.setVisible(true);
            this.setVisible(false);
            }else{
                showMessageDialog(null, "No se encontro");
            }  
        }else{
            showMessageDialog(null, "Ingrese una ID");
        }
        
    }//GEN-LAST:event_btnModificarUMouseClicked

    private void btnSalirUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirUActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirUActionPerformed

    private void btnEliminarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarUMouseClicked
        String id = jTextField1.getText();
        UsuarioDAO user = new UsuarioDAO();
        Usuario u; 
        if(id.length()!=0){
        u = user.buscar(Integer.parseInt(id));
        if(u!=null){
            user.eliminar(u);
            jTableUsers.setModel(usuarioDAO.tabla());
            jTextField1.setText("");
        
        }else{
            showMessageDialog(null, "No se encontro");
        }
         }else{
            showMessageDialog(null, "Ingrese una ID");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarUMouseClicked

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
        
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEliminarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GENERAL;
    private javax.swing.JPanel LEFT;
    private javax.swing.JPanel RIGHT;
    private javax.swing.JButton btnEliminarU;
    private javax.swing.JButton btnModificarU;
    private javax.swing.JButton btnSalirU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
