/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto.interfaces2;

import com.proyecto.interfaces2.Inventario.Inventario;
import com.proyecto.interfaces2.compras.Compras;
import com.proyecto.interfaces2.proveedores.VerProveedores;
import com.proyecto.interfaces2.users.VerUsers;
import com.proyecto.interfaces2.ventas.Ventas;
import com.proyecto.modelo.Usuario;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author alexa
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    Usuario usuario = new Usuario();
    
    public Menu2(Usuario u){
        this.usuario=u;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Menu2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GENERAL = new javax.swing.JPanel();
        LEFT = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RIGHT = new javax.swing.JPanel();
        mProveedores = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mCompras = new javax.swing.JLabel();
        mVentas = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        brRight = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GENERAL.setPreferredSize(new java.awt.Dimension(900, 600));
        GENERAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LEFT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Moon-Korean");
        LEFT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("../img/main-left.png"))); // NOI18N
        LEFT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        GENERAL.add(LEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 600));

        RIGHT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GENERAL.add(RIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        mProveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mProveedores.setForeground(new java.awt.Color(51, 51, 51));
        mProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("../img/proveedor-main.png"))); // NOI18N
        mProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mProveedoresMouseClicked(evt);
            }
        });
        GENERAL.add(mProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 100, 100));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Proveedores");
        GENERAL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, 10));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("ACEPTAR");
        GENERAL.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, -1, -1));

        mCompras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mCompras.setForeground(new java.awt.Color(51, 51, 51));
        mCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("../img/mCompras.png"))); // NOI18N
        mCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mComprasMouseClicked(evt);
            }
        });
        GENERAL.add(mCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 100, 100));

        mVentas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mVentas.setForeground(new java.awt.Color(51, 51, 51));
        mVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("../img/mVentas.png"))); // NOI18N
        mVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVentasMouseClicked(evt);
            }
        });
        GENERAL.add(mVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 100, 100));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ventas");
        GENERAL.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Compras");
        GENERAL.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, 10));

        brRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("../img/main-right2.png"))); // NOI18N
        GENERAL.add(brRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GENERAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GENERAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mComprasMouseClicked
       Compras com = new Compras(usuario);
       com.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_mComprasMouseClicked

    private void mVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVentasMouseClicked
    Ventas v = new Ventas(usuario);
    v.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_mVentasMouseClicked

    private void mProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mProveedoresMouseClicked
        VerProveedores prov = new VerProveedores(usuario);
        prov.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_mProveedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GENERAL;
    private javax.swing.JPanel LEFT;
    private javax.swing.JPanel RIGHT;
    private javax.swing.JLabel brRight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mCompras;
    private javax.swing.JLabel mProveedores;
    private javax.swing.JLabel mVentas;
    // End of variables declaration//GEN-END:variables
}
